config/routes.rb
Rails.application.routes.draw do
	get '/', to: redirect('/boards')

	match '/auth/:provider/callback', to: 'authentication#login', via: :all
	get '/logout', to: 'authentication#logout', as: 'logout'

	resource :user, controller: :authentication

	resources :boards do
		resources :posts, except: :index do
			resources :comments do #-> url.com/boards/:id/posts/:post_id/comments/:id
				member do
					post 'vote'
				end
			end

			member do
				post 'vote'
			end
		end
	end

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
	has_many :posts, dependent: :destroy
	belongs_to :owner, class_name: 'User'
end

app/models/comment.rb
require 'voted_model'

class Comment < ApplicationRecord
	belongs_to :post
	belongs_to :user
	belongs_to :parent, class_name: 'Comment', optional: true
	has_many :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy
	has_many :comment_votes, dependent: :destroy

	include VotedModel

	def display_name viewing_user
		if anonymous
			return 'Anonymous (me)' if viewing_user == user
			return 'Anonymous'
		end

		return user.alias
	end

	def votes
		comment_votes
	end
end

app/models/comment_vote.rb
require 'voted_model'

class CommentVote < ApplicationRecord
	belongs_to :user
	belongs_to :comment

	extend VoteModel
	init_status
end

app/models/post.rb
require 'voted_model'

class Post < ApplicationRecord
	belongs_to :board
	belongs_to :owner, class_name: 'User'
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 4 }
	has_many :post_votes, dependent: :destroy

	include VotedModel

	def votes
		post_votes
	end
end

app/models/post_vote.rb
require 'voted_model'

class PostVote < ApplicationRecord
	belongs_to :user
	belongs_to :post

	extend VoteModel
	init_status
end

app/models/user.rb
class User < ApplicationRecord
	has_many :comments, dependent: :destroy
	has_many :boards, dependent: :destroy

	def self.from_omni(auth)
		User.find_by(uid: auth[:uid]) || create_from_omni(auth)
	end

	def session
		session = {
				user_id: id,
				email: email
		}

		return session
	end

	def self.from_session session
		if session[:user] == nil
			return nil
		end

		user_id = session[:user]['user_id']
		if user_id == nil
			return nil
		end

		return User.find_by! id: user_id
	end

	private
	def self.create_from_omni(auth)
		create! do |u|
			u.uid = auth[:uid]
			u.email = auth[:info][:email]
			u.alias = u.email.split('@')[0]
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Simple auth helper for all controllers.
  def authenticate_user
    user = User.from_session session
    if user == nil
      redirect_to '/auth/nas_auth'
      return nil
    end
    # I like explicitly saying 'return' its more readable
    return user
  end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
	skip_before_filter :verify_authenticity_token

	def login
		@user = User.from_omni(auth_hash)

		session[:user] = @user.session

		redirect_to boards_path
	end

	def logout
		session[:user] = nil

		redirect_to boards_path
	end

	def edit
		@user = authenticate_user
	end

	def update
		@user = authenticate_user
		#check if the alias is already taken
		if User.where(alias: params[:user][:alias]).empty?
			@user.update(alias: params[:user][:alias])
		else
			flash.alert = "User name/alias taken"
		end

		redirect_to user_path
	end

	def show
		@user = authenticate_user
	end

	def destroy
		return unless authenticate_user

		logout

		@user.destroy
	end

	protected

	def auth_hash
		request.env['omniauth.auth']
	end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
	def index
		@boards = Board.all
	end

	def show
		@board = Board.find params[:id]
		@posts = @board.posts

	end

	def new
		authenticate_user
	end

	def create
		user = authenticate_user
		return if user == nil

		@board = Board.create!(params.require(:board).permit(:name)) do |b|
			b.owner = user
		end

		redirect_to @board
	end

	def destroy
		user = authenticate_user
		return if user == nil

		@board = Board.find params[:id]

		if @board.owner != user
			redirect_to board_path(@board)
			return
		end

		@board.delete
		redirect_to boards_path
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])

		user = User.from_session session
		if user == nil
			redirect_back fallback_location: board_post_path(@post.board, @post), alert: 'You must be logged in to comment'
			return
		end

		@comment = @post.comments.create! comment_params do |c|
			c.user = user
		end

		# redirects to the sender (in this case the post)
		redirect_back fallback_location: board_post_path(@post.board, @post)
	end

	def destroy
		user = authenticate_user
		return if user == nil

		@comment = Comment.find(params[:id])
		@post = @comment.post

		if @comment.user != user
			redirect_back fallback_location: board_post_path(@post.board, @post), alert: 'You do not own this post!'
			return
		end

		# delete the comment
		@comment.destroy

		# reload the previous page
		redirect_back fallback_location: board_post_path(@post.board, @post)
	end

	def edit
		@comment = Comment.find(params[:id])
		@post = @comment.post
	end

	def update
		@comment = Comment.find(params[:id])

		if @comment.update(comment_params)
			redirect_to board_post_path(@comment.post.board, @comment.post)
		else
			render 'edit'
		end
	end

	# TODO: Merge with vote in posts_controller
	def vote
		user = authenticate_user
		return if user == nil

		@comment = Comment.find(params[:id])
		mode = params[:mode]

		@comment.comment_votes.where(comment: @comment, user: user).destroy_all

		if mode == 'up_vote' or mode == 'down_vote'
			@comment.comment_votes.create(comment: @comment, user: user, status: mode.to_sym)
		end
	end

	private
	def comment_params
		params.require(:comment).permit(:parent_id, :commenter, :body, :anonymous)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def show
		@post = Post.find(params[:id])
		@comments = @post.comments.where parent: nil
	end

	def new
		@board = Board.find params[:board_id]
		authenticate_user
	end

	def create
		user = authenticate_user
		return if user == nil

		@board = Board.find params[:board_id]

		@post = Post.create! params.require(:post).permit(:title, :contents) do |p|
			p.board = @board
			p.owner = user
		end

		redirect_to board_post_path(@board, @post)
	end

	def edit
	end

	def update
	end

	# TODO: Merge with vote in comments_controller
	def vote
		user = authenticate_user
		return if user == nil

		@post = Post.find(params[:id])
		mode = params[:mode]

		@post.post_votes.where(post: @post, user: user).destroy_all

		if mode == 'up_vote' or mode == 'down_vote'
			@post.post_votes.create(post: @post, user: user, status: mode.to_sym)
		end
	end

	def destroy
		user = authenticate_user
		return if user == nil

		@post = Post.find params[:id]

		if @post.owner != user
			redirect_to board_post_path(@post.board, @post)
			return
		end

		@post.delete
		redirect_to board_path(@post.board)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
	def current_user
		User.from_session session
	end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/ui_helper.rb
module UiHelper
	def dropdown_box(&block)
		panel = content_tag :div,
												capture(&block),
												class: 'dropdown-panel'

		content_tag :span,
								'&#x25BC;'.html_safe + panel,
								class: 'dropdown'
	end
end

app/views/authentication/edit.html.erb
<h1>changing alias for: <%=@user.alias %></h1></br>
<h4>New alias:</h4>
<%= form_for @user, method: :patch do |f| %>
	<p>
		<%= f.text_field :alias %>
	</p>
		<p>
			<%= f.submit %>
		</p>
<% end %>

app/views/authentication/show.html.erb
<%= content_tag :h1, 'Profile for ' + @user.alias %>

<hr/>


<%= link_to 'change alias', edit_user_path%>

<%= link_to 'Delete Account', user_path,
						method: :delete,
						data: {confirm: 'Are you sure?'} %>
<hr/>
<%= content_tag :h2, 'Comments:' %>

<ul class="comments-list comments-root">
	<%= render partial: 'comments/comment', collection: @user.comments, locals: {recurse: false, reply: false} %>
</ul>

app/views/boards/index.html.erb
<%= dropdown_box do %>
		<%= link_to 'New Board', new_board_path %>
<% end %><h1>Boards:</h1>

<ul class="item-list">
	<% @boards.each do |b| %>
			<li><%= link_to b.name, b %></li>
	<% end %>
</ul>

app/views/boards/new.html.erb
<h1>Create Board:</h1>

<%= form_for :board, url: boards_path do |f| %>
		<p>
			<%= f.label :name %><br>
			<%= f.text_field :name %>
		</p>

		<p>
			<%= f.submit %>
		</p>
<% end %>

app/views/boards/show.html.erb
<%= dropdown_box do %>
		<%= link_to 'Delete Board', board_path(@board),
								method: :delete,
								data: {confirm: 'Are you sure?'} %><br/>

		<%= link_to 'Add Post', new_board_post_path(@board) %>
<% end %><h1><%= @board.name %></h1>
<%= content_tag :h2, @board.owner.alias %>

<ul class="item-list">
	<% @posts.each do |p| %>
			<li><%= p.vote_score %> <%= link_to p.title, board_post_path(@board, p) %></li>
	<% end %>
</ul>

app/views/comments/_comment.html.erb
<li>
	<%= content_tag :div, 'data-comment-id': comment.id,
									'data-comment-path': vote_board_post_comment_path(comment.post.board, comment.post, comment) do %>
			By <%= comment.display_name current_user %>, <%= pluralize comment.vote_score, 'upvote' %><br/>
			<%= content_tag :p, comment.body %>
			<% unless current_user == nil or (defined? reply and not reply) %>
					<%= content_tag :span, 'reply', class: 'reply-bttn post-bttn' %>
					<% if comment.user == current_user %>
							<%= link_to 'edit', edit_board_post_comment_path(@post.board, @post, comment), class: 'post-bttn' %>
							<%= link_to 'delete', board_post_comment_path(@post.board, @post, comment),
													class: 'post-bttn',
													method: :delete,
													data: {confirm: 'Are you sure?'} %>
					<% end %>
					<%= content_tag :span, 'upvote', class: 'vote-bttn post-bttn', 'data-vote': 'up_vote' %>
					<%= content_tag :span, 'unvote', class: 'vote-bttn post-bttn', 'data-vote': 'no_vote' %>
					<%= content_tag :span, 'downvote', class: 'vote-bttn post-bttn', 'data-vote': 'down_vote' %>
			<% end %>
	<% end %>

	<% if comment.replies.any? and (not defined? recurse or recurse) %>
			<ul class="comments-list">
				<%= render comment.replies %>
			</ul>
	<% end %>
</li>

app/views/comments/_form.html.erb
<% com = (defined? comment) ? comment : Comment.new %>
<% id = (defined? form_id) ? form_id : 'new_comment' %>
<%= form_for [@post.board, @post, com], html: {id: id} do |f| %>
		<%= hidden_field_tag 'comment[parent_id]' %>
		<p>
			<%= f.label :body %><br>
			<%= f.text_area :body %>
		</p>
		<p>
			<%= f.label :anonymous %><%= f.check_box :anonymous %>
		</p>
		<p>
			<%= f.submit %>
		</p>
<% end %>

app/views/comments/edit.html.erb
<%= render :partial => 'comments/form', locals: {comment: @comment} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Anonamit</title>
		<%= csrf_meta_tags %>

		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>

	<body>
		<script>
		window.app.teledata = {
			controller: "<%= params[:controller] %>",
			action: "<%= params[:action] %>"
		};
		</script>
		<nav>
			<%= link_to 'NAS-Chan', boards_path, class: 'title' %>
			<% if session[:user] then %>
					<%= link_to current_user.alias, user_path %><%= link_to 'Logout', logout_path %>
			<% else %>
					<%= link_to 'NAS-Auth', '/auth/nas_auth' %>
					<%= link_to 'Dev Auth', '/auth/developer' unless Rails.env.production? %>
			<% end %>
		</nav>
		<div id="main-contents">
			<% flash.each do |key, value| %>
					<%= content_tag :div, class: ['alert', 'alert-' + key] do %>
							<%= value %>
					<% end %>
			<% end %>
			<div id="full">
				<%= yield %>
			</div>
		</div>
	</body>
</html>

app/views/posts/new.html.erb
<h1>Create Board:</h1>

<%= form_for :post, url: board_posts_path(@board) do |f| %>
		<p>
			<%= f.label :title %><br>
			<%= f.text_field :title %>
		</p>

		<p>
			<%= f.label :contents %><br>
			<%= f.text_area :contents %>
		</p>

		<p>
			<%= f.submit %>
		</p>
<% end %>

app/views/posts/show.html.erb
<%= dropdown_box do %>
		<%= link_to 'Delete Post', board_post_path(@post.board, @post),
								method: :delete,
								data: {confirm: 'Are you sure?'} %>
<% end %><h1><%= @post.title %></h1>

<%= content_tag :p, 'By ' + @post.owner.alias %>
<%= content_tag :p, pluralize(@post.vote_score, 'upvote') %>
<%= content_tag :p, @post.contents %>

<%= content_tag :span, 'upvote', class: 'post-vote-bttn post-bttn', 'data-vote': 'up_vote' %>
<%= content_tag :span, 'unvote', class: 'post-vote-bttn post-bttn', 'data-vote': 'no_vote' %>
<%= content_tag :span, 'downvote', class: 'post-vote-bttn post-bttn', 'data-vote': 'down_vote' %>

<!-- TODO: Merge with template -->
<%= content_tag :div, id: 'reply-form', style: 'display: none;' do %>
		<%= content_tag :div, class: 'reply-area' do %>
				Reply:
				<%= render :partial => 'comments/form', locals: {form_id: 'edit_comment'} %>
				<%= content_tag :span, 'cancel', class: 'post-bttn cancel-reply-bttn' %>
		<% end %>
<% end %>

<%= dropdown_box do %>
		<h2>Add comment:</h2>
		<%= render :partial => 'comments/form' %>
<% end %>


<h2>Comments</h2>
<!--TODO there is always one blank comment?-->
<ul class="comments-list comments-root">
	<% if @comments.any? %>
			<%= render @comments %>
	<% else %>
			<h4>There are no comments</h4>
	<% end %>
</ul>


<!-- nav links here -->
<%= link_to 'Back', board_path(@post.board) %>